language: generic

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "translator-app"
  env: "Translator-app-env"

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  bucket_name: "translatorappbucker"

  bucket_path: "docker"

  on:
    branch: master